### ISSUE TITLE
Inconsistency between different ways of specifying totaldegree

### ISSUE THREAD

**Issue by JPDarby** [ACEsuit/ACEpotentials.jl#174]
```
using ACEpotentials

model1 = acemodel(;order=4, totaldegree=[20,20,20,20], Eref=Dict("Si" => -158.54496821), elements=[:Si])
model2 = acemodel(;order=4, totaldegree=20, Eref=Dict("Si" => -158.54496821), elements=[:Si])
@show length(model1.basis) length(model2.basis)
```
produces
```
length(model1.basis) = 5434
length(model2.basis) = 5456
```

**Comment by cortner** [comment]
Curious, I have a vague idea deeply buried inside ACE1.jl... Thanks for reporting. 

do you also find the models have different performance?

**Comment by cortner** [comment]
I'm going to close this. But if there is any concern around it we can reopen.

**Comment by wcwitt** [comment]
I think this is important, no? Partly because I have seen other examples where the basis has a different size from what I expected.

However, if the argument is that this is an ACE1 problem, soon to be irrelevant, I can accept that.

**Comment by cortner** [comment]
I actually dont think it is that important, only confusing. The way multi-degrees are implemented in ACE1 (hack) allows a roundoff error. So most likely because of that, there are some basis functions at the high resolution end that get "quasi-randomly" added to the basis or not. 

The analogous implementation in ACEpotentials is much cleaner and no such discrepancy should arise.

**Comment by wcwitt** [comment]
> The analogous implementation in ACEpotentials is much cleaner and no such discrepancy should arise.

This I can live with.
