### ISSUE TITLE
Not preconditioners, but priors

### ISSUE THREAD

**Issue by gelzinyte** [ACEsuit/ACEpotentials.jl#29]
Rename to reflect that what we currently call "preconditioners" are actually priors.

**Comment by cortner** [comment]
@gabor1 @casv2 @davkovacs -- getting some representative opinions ... 

at the moment the code is conflating the terms preconditioned and prior/regularizer. Granted they are not entirely unrelated but I think for parameter estimation we should not use the term preconditioner. 

I think either prior or regularizer would be fine. Since we are thinking of moving back towards a more bayesian perspective maybe prior is good? Would you feel comfortable if we use "prior" even when we don't do proper Bayesian regression but just use it via analogy?

**Comment by davkovacs** [comment]
I would not be opposed to calling it a prior, even if we combine it with a non-Bayesian solver.

**Comment by gabor1** [comment]
I would prefer "regulariser" when it's not rigorously a Bayesian prior.

— Gábor

Gabor Csanyi
Professor of Molecular Modelling
Engineering Laboratory
University of Cambridge

------- Original Message -------

**Comment by cortner** [comment]
Ok so call it regulariser and when In  a Bayesian context we use a regulariser to specify the prior. Does this make logical sense to everybody?
