### ISSUE TITLE
Simplify and document generation of (per-site) descriptors

### ISSUE THREAD

**Issue by wcwitt** [ACEsuit/ACEpotentials.jl#35]
Quick summary of a Slack discussion from 16-18 July 2022.

"before I fit a potential I would like to just evaluate the basis for an atomic structure, i.e. get an array of basis values for each site. Can someone please put such an example into this tutorial?"

Options mentioned
* `site_energy(B, at, 1)` where 1 is atom index, at is atoms object and B is ACE basis
* `evaluate_basis(B, at)`

There was some disagreement about whether `site_energy(B, at, 1)` is adequate or confusing. It provides the energy basis evaluated for a site, and the total site energy for a potential `IP` is something like
```
site_energy(IP, at, 1) = sum(coeff .* site_energy(B, at, 1))
```

One thought: Would `site_descriptor(B, at, 1)` be more clear than `site_energy(B, at, 1)`? More generally, we need to discuss, decide whether to make any changes, and document.

**Comment by cortner** [comment]
`evaluate_basis(basis, args...)` doesn't work for me. The fact it's a basis we are evaluating is already encoded in the argument. From the discussion on Slack I suggest: 
* `evaluate(basis, atomic_env)` : the current evaluate
* `evaluate(basis, structure)` : the current `energy`
And then, `energy` would just become an alias. 

Next - do we need an alias for `evaluate` that sounds more like "evaluate the descriptor"? The `site_descriptor` could just be achieved via 
```julia
evaluate(basis, at, 1)
```
Instead of additional syntax for evaluating *all* the per-site descriptors we could allow 
```julia
evaluate(basis, at, [2,3,5,10]) # for a few site descriptors
evaluate(basis, at, :)  # for all site descriptors.
```
But maybe this is getting too cryptic now and the `site_descriptor` and `site_descriptors` syntax will be clearer. (Or could again be aliases...)

**Comment by wcwitt** [comment]
I added a very basic tutorial addressing this a while ago: https://acesuit.github.io/ACE1pack.jl/dev/literate_tutorials/descriptor/.

So I vote we close for now and revisit when necessary?

**Comment by cortner** [comment]
what about the terminology, that's not really settled yet.

**Comment by cortner** [comment]
@wcwitt  --  A few people at UBC that are starting to use ACE as features for classification and data analysis tasks. So I'd like to come back to this, make this functionatlity convenient to access and then close this. 

Maybe `site_descriptors` and output a matrix of descriptors is the best choice? And `site_descriptor(..., i)` which is now `site_energy` so just an alias for better readability.

**Comment by wcwitt** [comment]
The first version is done - we can revisit if necessary
